// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/archive": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/archive";
  };
  "routes/layout.tsx": {
    id: "routes/layout";
    page: "/" | "/archive";
  };
  "routes/history.tsx": {
    id: "routes/history";
    page: "/";
  };
  "routes/archive.tsx": {
    id: "routes/archive";
    page: "/archive";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "routes/layout": typeof import("./src/app/routes/layout.tsx");
  "routes/history": typeof import("./src/app/routes/history.tsx");
  "routes/archive": typeof import("./src/app/routes/archive.tsx");
};